# clusters/my-minikube-cluster/fleetman-apps.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: fleetman-apps
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/my-minikube-cluster # <--- CRITICAL CHANGE: Points to the directory where all app YAMLs now live
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system