apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker-service
  namespace: minikube-tomcat # Deploy in our dedicated namespace
spec:
  selector:
    app: position-tracker
  ports:
    - protocol: TCP
      port: 8080 # Service port
      targetPort: 8080 # Container port
  type: ClusterIP # Only accessible within the cluster