# clusters/my-minikube-cluster/fleetman-apps.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: fleetman-apps
  namespace: flux-system
spec:
  interval: 1m0s
  path: clusters/my-minikube-cluster/kubernetes-manifests # Removed leading ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: fleetman-api-gateway-deployment
      namespace: minikube-tomcat
    - apiVersion: apps/v1
      kind: Deployment
      name: fleetman-position-tracker-deployment
      namespace: minikube-tomcat
    - apiVersion: apps/v1
      kind: Deployment
      name: fleetman-position-simulator-deployment
      namespace: minikube-tomcat
    - apiVersion: apps/v1
      kind: Deployment
      name: fleetman-webapp-angular-deployment
      namespace: minikube-tomcat