apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-simulator-service
  namespace: minikube-tomcat
spec:
  selector:
    app: position-simulator
  ports:
    - protocol: TCP
      port: 8080 # Service port (if it exposes any, otherwise can be omitted)
      targetPort: 8080 # Container port
  type: ClusterIP # Only accessible within the cluster