apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-position-simulator-deployment
  namespace: minikube-tomcat
  labels:
    app: position-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: position-simulator
  template:
    metadata:
      labels:
        app: position-simulator
    spec:
      containers:
      - name: position-simulator
        image: fleetman/position-simulator:latest
        imagePullPolicy: Never # Crucial for Minikube
        env:
        - name: POSITION_TRACKER_HOSTNAME
          value: "fleetman-position-tracker-service" # Kubernetes Service name for Position Tracker
        - name: POSITION_TRACKER_PORT
          value: "8080"
        # NEW: Add the missing queue name environment variable
        - name: FLEETMAN_POSITION_QUEUE
          value: "position.queue" # Common queue name