apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp-angular-service
  namespace: minikube-tomcat
spec:
  selector:
    app: webapp-angular
  ports:
    - protocol: TCP
      port: 80 # Service port
      targetPort: 80 # Container port (Nginx)
      nodePort: 30082 # Choose an available NodePort, e.g., 30082
  type: NodePort # Expose for external access