# fleetman-webapp-angular-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp-angular
spec:
  selector:
    app: fleetman-webapp-angular
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer # Use LoadBalancer for external access, or ClusterIP if using Ingress