apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp-angular-service
  namespace: minikube-tomcat
spec:
  selector:
    app: fleetman-webapp-angular
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: NodePort