# fleetman-webapp-angular-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-webapp-angular-deployment
  namespace: minikube-tomcat
  labels:
    app: fleetman-webapp-angular
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman-webapp-angular
  template:
    metadata:
      labels:
        app: fleetman-webapp-angular
    spec:
      containers:
        - name: fleetman-webapp-angular
          image: richardchesterwood/k8s-fleetman-webapp-angular:release2-multi
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5