# fleetman-position-tracker-app-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: fleetman-position-tracker-app-config
  namespace: minikube-tomcat
data:
  application.properties: |
    # Spring Boot profile
    spring.profiles.active=kubernetes

    # RabbitMQ Configuration
    spring.rabbitmq.addresses=rabbitmq-service.minikube-tomcat.svc.cluster.local:5672
    spring.rabbitmq.listener.simple.auto-startup=true # Ensure listener starts

    # MySQL Datasource Configuration
    spring.datasource.url=jdbc:mysql://mysql-service.minikube-tomcat.svc.cluster.local:3306/fleetman?useSSL=false
    spring.datasource.username=root
    spring.datasource.password=admin # <--- CONFIRM YOUR ACTUAL MYSQL ROOT PASSWORD HERE

    # Fleetman specific queue name
    fleetman.position.queue=position-queue

    # Server port (if not default 8080)
    server.port=8080

    # Disable embedded ActiveMQ if it's causing issues (if present in original app)
    # spring.activemq.enabled=false