apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway-service
  namespace: minikube-tomcat
spec:
  selector:
    app: fleetman-api-gateway
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: NodePort