apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker-service
  namespace: minikube-tomcat
spec:
  selector:
    app: fleetman-position-tracker
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: NodePort