# fleetman-position-simulator-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-simulator
spec:
  selector:
    app: fleetman-position-simulator
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP # Internal service, no external access needed