apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: minikube-tomcat # CHANGED: Dedicated namespace
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "your_root_password" # <<< CHANGE THIS PASSWORD
        - name: MYSQL_DATABASE
          value: "myappdb"
        - name: MYSQL_USER
          value: "appuser"
        - name: MYSQL_PASSWORD
          value: "your_app_password" # <<< CHANGE THIS PASSWORD
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
