apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: minikube-tomcat # CHANGED: Dedicated namespace
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP # Only accessible within the cluster by other pods
