apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  namespace: minikube-tomcat # Deploy in our dedicated namespace
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management # Image with management UI
        ports:
        - containerPort: 5672 # AMQP port
        - containerPort: 15672 # Management UI port
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "guest" # Default user
        - name: RABBITMQ_DEFAULT_PASS
          value: "guest" # Default password (change for production!)